const data = {
  basicInfo: [
    {
      id: 0,
      label: "First Name",
      value: "",
      placeholder: "Lester",
      inputType: "input",
      type: "text",
    },
    {
      id: 1,
      label: "Last Name",
      value: "",
      placeholder: "Escarlan",
      inputType: "input",
      type: "text",
    },
    {
      id: 2,
      label: "Address",
      value: "",
      placeholder: "Taga Bundok",
      inputType: "input",
      type: "text",
    },
    {
      id: 3,
      label: "Email",
      value: "",
      placeholder: "jn@pogi.com",
      inputType: "input",
      type: "email",
    },
    {
      id: 4,
      label: "Phone Number",
      value: "",
      placeholder: "+639957128195",
      inputType: "input",
      type: "tel",
    },
  ],

  educationInfo: [
    {
      id: 0,
      label: "School Name",
      value: "",
      placeholder: "XYZ University",
      inputType: "input",
      type: "text",
    },
    {
      id: 1,
      label: "Location",
      value: "",
      placeholder: "Sa Gilid lang",
      inputType: "input",
      type: "text",
    },
    {
      id: 2,
      label: "Degree",
      value: "",
      placeholder: "BSc in Computer Science",
      inputType: "input",
      type: "text",
    },

    {
      id: 3,
      label: "Year Started",
      value: "",
      placeholder: "2020",
      inputType: "input",
      type: "text",
    },
    {
      id: 4,
      label: "Year Graduated",
      value: "",
      placeholder: "Present",
      inputType: "input",
      type: "text",
    },
  ],

  experienceInfo: [
    {
      id: 0,
      label: "Company Name",
      value: "",
      placeholder: "ABC Corp",
      type: "text",
      inputType: "input",
    },
    {
      id: 1,
      label: "Location",
      value: "",
      placeholder: "Sa Gilid lang",
      inputType: "input",
      type: "text",
    },
    {
      id: 2,
      label: "Role",
      value: "",
      placeholder: "Software Engineer",
      inputType: "input",
      type: "text",
    },
    {
      id: 3,
      label: "Main Responsibilities",
      value: "",
      placeholder: "Developed software for clients",
      inputType: "textarea",
      type: "text",
    },
    {
      id: 4,
      label: "Year Started",
      value: "",
      placeholder: "2020",
      inputType: "input",
      type: "text",
    },
    {
      id: 5,
      label: "Year Ended",
      value: "",
      placeholder: "",
      inputType: "input",
      type: "text",
    },
  ],
};

export default data;
